spring.application.name=loadnormas

# Configuración de Lucene
#lucene.index.directory=path/to/index
#lucene.index.directory=/Users/albertosanmartin/usach-memoria-implementacion/desarrollo/proyecto-normativo-ms/pipelinenormativosii/lucene-index
lucene.index.directory=/Users/albertosanmartin/Academic-Professional/usach-memoria-implementacion/desarrollo/proyecto-normativo-ms/pipelinenormativosii/lucene-index


# Configuración de SpringDoc OpenAPI (Swagger)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.display-operation-id=true
springdoc.swagger-ui.show-extensions=true
springdoc.swagger-ui.show-common-extensions=true

# Configuración del servidor
server.port=8080
server.servlet.context-path=/

